//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ustamdan.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustamdan… Yıllar önce Gaziantep’te tanıştığımız Mehmet Usta ile başladı bu serüven. Mehmet Usta’nın zanaatına olan aşkı, tutkusu  ve misafirine bahşettiği sohbeti ile bindik bu Anadolu teknesine. Bir hoş sohbetle başlayan, yerel değerlerimizi araştırdıkça demlenen ve ekip olunca güçlenen beraberlikten Ustamdan doğdu..
        /// </summary>
        public static string AboutStoryP1 {
            get {
                return ResourceManager.GetString("AboutStoryP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustamdan, kültür ve yerel emeği yaratıcı fikirlerle buluşturarak insanlara ulaştıran , ürün ve yazılar ile inşa edilen bir değer köprüsüdür.  Bu köprünün bir başında bakır döven eller öte başında emeğe kıymet veren eller uzanır..
        /// </summary>
        public static string AboutStoryP2 {
            get {
                return ResourceManager.GetString("AboutStoryP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustamdan’ı  kalıcı ve evrensel bir mecraya dönüştürmek için çalışıyor, Anadolu kültürüne şevkle emek veriyoruz..
        /// </summary>
        public static string AboutStoryP3 {
            get {
                return ResourceManager.GetString("AboutStoryP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kültür harmanında buluşmak üzere….
        /// </summary>
        public static string AboutStoryP4 {
            get {
                return ResourceManager.GetString("AboutStoryP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİKAYEMİZ.
        /// </summary>
        public static string AboutStoryTitle {
            get {
                return ResourceManager.GetString("AboutStoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKİBİMİZ.
        /// </summary>
        public static string AboutTeamTitle {
            get {
                return ResourceManager.GetString("AboutTeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/hakkimizda.
        /// </summary>
        public static string AboutUsLink {
            get {
                return ResourceManager.GetString("AboutUsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölgeler.
        /// </summary>
        public static string AreaTitle {
            get {
                return ResourceManager.GetString("AreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıhane.
        /// </summary>
        public static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KATEGORİLER.
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgilerimiz.
        /// </summary>
        public static string ContactAddressTitle {
            get {
                return ResourceManager.GetString("ContactAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/iletisim.
        /// </summary>
        public static string ContactLink {
            get {
                return ResourceManager.GetString("ContactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string EmailTemplateMessageText {
            get {
                return ResourceManager.GetString("EmailTemplateMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string EmailTemplateNameText {
            get {
                return ResourceManager.GetString("EmailTemplateNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string EmailTemplateSubjectText {
            get {
                return ResourceManager.GetString("EmailTemplateSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string EmailTemplateSubmitText {
            get {
                return ResourceManager.GetString("EmailTemplateSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıhaneden Son Yazılar.
        /// </summary>
        public static string IndexLatestPostsTitle {
            get {
                return ResourceManager.GetString("IndexLatestPostsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASINDA BİZ.
        /// </summary>
        public static string IndexNewsTitle {
            get {
                return ResourceManager.GetString("IndexNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZANAAT DOSTU ŞİRKETLER AİLESİ.
        /// </summary>
        public static string IndexPartnersTitle {
            get {
                return ResourceManager.GetString("IndexPartnersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi kurum çizginize özel zanaat koleksiyonunuzu yaratıyoruz. Hikayesi ve tarihi ile hayat bulan zanaatlar kurumunuzun kimliği ile bütünleşiyor..
        /// </summary>
        public static string IndexService1Text {
            get {
                return ResourceManager.GetString("IndexService1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum Zanaat Koleksİyonu.
        /// </summary>
        public static string IndexService1Title {
            get {
                return ResourceManager.GetString("IndexService1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal hediyeleriniz için ürün seçkisi oluşturuyoruz. Ustamdan’ın eşsiz ürünleri sayesinde çalışanlarınızı özel hissettirin..
        /// </summary>
        public static string IndexService2Text {
            get {
                return ResourceManager.GetString("IndexService2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal Hedİye Çözümlerİ.
        /// </summary>
        public static string IndexService2Title {
            get {
                return ResourceManager.GetString("IndexService2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yurtdışı ve yurtiçi kurumlara özel yerel üretim danışmanlığı veriyor, süreç takibi hizmeti sunuyoruz..
        /// </summary>
        public static string IndexService3Text {
            get {
                return ResourceManager.GetString("IndexService3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanaat Üretİm Danışmanlığı.
        /// </summary>
        public static string IndexService3Title {
            get {
                return ResourceManager.GetString("IndexService3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıhane yazar ailemizle kültürel ve yerel değerleri dijitale taşıyor, görünür hale geliyoruz..
        /// </summary>
        public static string IndexService4Text {
            get {
                return ResourceManager.GetString("IndexService4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kültürel İçerİk Üretİmİ.
        /// </summary>
        public static string IndexService4Title {
            get {
                return ResourceManager.GetString("IndexService4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİZMETLERİMİZ.
        /// </summary>
        public static string IndexServicesTitle {
            get {
                return ResourceManager.GetString("IndexServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustamdan, kültürü yaratıcı fikirlerle buluşturarak insanlara ulaştıran bir köprüdür..
        /// </summary>
        public static string IndexSliderText {
            get {
                return ResourceManager.GetString("IndexSliderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;BİR KÜLTÜR MOZAİĞİ&quot;.
        /// </summary>
        public static string IndexSliderTitle {
            get {
                return ResourceManager.GetString("IndexSliderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email&apos;inizi Giriniz.
        /// </summary>
        public static string IndexSubscriptionEmailText {
            get {
                return ResourceManager.GetString("IndexSubscriptionEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şimdi Abone Ol.
        /// </summary>
        public static string IndexSubscriptionSubmitText {
            get {
                return ResourceManager.GetString("IndexSubscriptionSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone olduğunuz için teşekkür ederiz...
        /// </summary>
        public static string IndexSubscriptionSuccessText {
            get {
                return ResourceManager.GetString("IndexSubscriptionSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÜLTENİMİZE ÜYE OLUN.
        /// </summary>
        public static string IndexSubscriptionTitle {
            get {
                return ResourceManager.GetString("IndexSubscriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkiye den seçilen üç sosyal girişim Silikon Vadisinde bizi temsil etti..
        /// </summary>
        public static string News1Content {
            get {
                return ResourceManager.GetString("News1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Sabah.
        /// </summary>
        public static string News1Title {
            get {
                return ResourceManager.GetString("News1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İki genç mühendisin Anadolu yu gezme tutkusu sayesinde Ustamdan doğdu..
        /// </summary>
        public static string News2Content {
            get {
                return ResourceManager.GetString("News2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORBES TURKIYE.
        /// </summary>
        public static string News2Title {
            get {
                return ResourceManager.GetString("News2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;“Bin Yıllık Ellerden Anadolu Zanaatları”&lt;/i&gt; sloganıyla yola çıktılar.
        /// </summary>
        public static string News3Content {
            get {
                return ResourceManager.GetString("News3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anadolu Jet Skylife.
        /// </summary>
        public static string News3Title {
            get {
                return ResourceManager.GetString("News3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABD başkanı Barack Obama tarafından desteklenen ve düzenlediği Obama yönetimi, Küresel Girişimcilik Zirvesi (GES) başarılı üç Türk kadın girişimcileri ağırladı..
        /// </summary>
        public static string News4Content {
            get {
                return ResourceManager.GetString("News4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuşak Haber.
        /// </summary>
        public static string News4Title {
            get {
                return ResourceManager.GetString("News4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;/&quot;&gt;Ustamdan.com&lt;/a&gt; girişimi, yerel pazarların sürdürülebilirliğini artırmak, yörelerin tarihsel ve kültürel değerlerini gelecek nesillere aktarmak bununla birlikte işi hikayeleştirerek yöresel turizme de katkı sağlama amacını taşıyor..
        /// </summary>
        public static string News5Content {
            get {
                return ResourceManager.GetString("News5Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webrazzi.
        /// </summary>
        public static string News5Title {
            get {
                return ResourceManager.GetString("News5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakamlar &apos;Gençlerin topluma katılımındaki politikalar eksik&apos; diyor. Çözüm üretmeye çalışan gençlerin hikâyeleri ise umut veriyor..
        /// </summary>
        public static string News6Content {
            get {
                return ResourceManager.GetString("News6Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALJAZEERA.
        /// </summary>
        public static string News6Title {
            get {
                return ResourceManager.GetString("News6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        public static string OurStoryTitle {
            get {
                return ResourceManager.GetString("OurStoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Eklenenler.
        /// </summary>
        public static string PostLatestsTitle {
            get {
                return ResourceManager.GetString("PostLatestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını Oku.
        /// </summary>
        public static string PostReadMoreText {
            get {
                return ResourceManager.GetString("PostReadMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzer Yazılar.
        /// </summary>
        public static string PostRelatedText {
            get {
                return ResourceManager.GetString("PostRelatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Yazıyı Paylaş:.
        /// </summary>
        public static string PostShareText {
            get {
                return ResourceManager.GetString("PostShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Bulutu.
        /// </summary>
        public static string PostTagCloudText {
            get {
                return ResourceManager.GetString("PostTagCloudText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/ara.
        /// </summary>
        public static string SearchLink {
            get {
                return ResourceManager.GetString("SearchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Yapın...
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Sonuçları.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Email Gönderin.
        /// </summary>
        public static string SendUsEmailText {
            get {
                return ResourceManager.GetString("SendUsEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurucu Ortak.
        /// </summary>
        public static string TeamPosition1 {
            get {
                return ResourceManager.GetString("TeamPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Yayın Yönetmeni.
        /// </summary>
        public static string TeamPosition2 {
            get {
                return ResourceManager.GetString("TeamPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Etki Yönetimi ve Yazar.
        /// </summary>
        public static string TeamPosition3 {
            get {
                return ResourceManager.GetString("TeamPosition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar.
        /// </summary>
        public static string TeamPosition4 {
            get {
                return ResourceManager.GetString("TeamPosition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarik Sorumlusu.
        /// </summary>
        public static string TeamPosition5 {
            get {
                return ResourceManager.GetString("TeamPosition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercüman.
        /// </summary>
        public static string TeamPosition6 {
            get {
                return ResourceManager.GetString("TeamPosition6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar.
        /// </summary>
        public static string TeamPosition7 {
            get {
                return ResourceManager.GetString("TeamPosition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar.
        /// </summary>
        public static string TeamPosition8 {
            get {
                return ResourceManager.GetString("TeamPosition8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazılım Uzmanı.
        /// </summary>
        public static string TeamPosition9 {
            get {
                return ResourceManager.GetString("TeamPosition9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tr/yazihane.
        /// </summary>
        public static string WeeklyLink {
            get {
                return ResourceManager.GetString("WeeklyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anadolu KÜltÜr BloĞu.
        /// </summary>
        public static string WeeklyTitle {
            get {
                return ResourceManager.GetString("WeeklyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazılar.
        /// </summary>
        public static string WeeklyTitle2 {
            get {
                return ResourceManager.GetString("WeeklyTitle2", resourceCulture);
            }
        }
    }
}
